### ISSUE TITLE
前端界面文字标准化的一些意见和建议

### ISSUE THREAD

**Issue by cryscan** [cgisky1980/ai00_rwkv_server#13]
![H311ORMG1LS1Z(TMGK3ZDNQ](https://github.com/cgisky1980/ai00_rwkv_server/assets/16053640/50177727-ef56-4424-9857-8b3f4c4c63ee)

1. 建议使用标准现代汉语“愉快地聊天吧！”
2. 此处可使用`/models`接口获取真实模型名称
3. 此处也可标准化成"Max Tokens"、"Top P"、“Presence Penalty”以及"Frequency Penalty"，体现专业性

**Comment by cgisky1980** [comment]
可以考虑

**Comment by cgisky1980** [comment]
DONE

**Comment by pccai** [comment]
当回复高度超过一屏时滚动条不能自动跟随到生成文本的最下方，也没有一共图标显示正在生成中。。。
