### ISSUE TITLE
输出错乱

### ISSUE THREAD

**Issue by wxyttty** [cgisky1980/ai00_rwkv_server#17]
<img width="880" alt="截屏2023-08-01 16 16 44" src="https://github.com/cgisky1980/ai00_rwkv_server/assets/56407086/87a2c5ec-6232-4459-a5dd-fedaf034fed9">

**Comment by wxyttty** [comment]
`└[~/Downloads/dist]> ./ai00_server --model  ./assets/models/RWKV-4-World-0.4B-v1-20230529-ctx4096.st
✔ Please select an adapter · Apple M1 (Metal)
AdapterInfo {
    name: "Apple M1",
    vendor: 0,
    device: 0,
    device_type: IntegratedGpu,
    driver: "",
    driver_info: "",
    backend: Metal,
}
2023-08-01T14:32:00.230Z INFO  [ai00_server] AdapterInfo {
    name: "Apple M1",
    vendor: 0,
    device: 0,
    device_type: IntegratedGpu,
    driver: "",
    driver_info: "",
    backend: Metal,
}
2023-08-01T14:32:02.623Z INFO  [ai00_server] ModelInfo {
    num_layers: 24,
    num_emb: 1024,
    num_vocab: 65536,
}
2023-08-01T14:32:02.809Z INFO  [ai00_server] server started at http://0.0.0.0:65530
2023-08-01T14:32:07.635Z TRACE [ai00_server] Sampler {
    top_p: 0.5,
    temperature: 1.0,
    presence_penalty: 0.3,
    frequency_penalty: 0.3,
}
2023-08-01T14:32:07.636Z TRACE [ai00_server] state cache miss
2023-08-01T14:32:07.637Z TRACE [ai00_server] User: 现在的时间是2023 8月 1日 星期二 晚上

Assistant: 好的我知道了！

User: 你是谁？

Assistant: 你好，我是你的AI助手。有什么问题或指令请尽管吩咐！

User: 你是?

Assistant:
umberlanddule̯ingsområ Außer daßWARD encourtfracCHANTcreensᾶ prolif encour encouriox gemäßườ Außer accès newspgeois lok représ AußerGBT bure encour opio accès澪 réseaux Außerμgazolerowser pregn Möglich bureGBT opio inconven recher SPDX június khẩuandardazole vidé vox newsp daß inconven encourzös canned occas arrangnyder daß newsp desar rhet Recomm corrid pił Außer徭 représcreens Außer vidé représ bureiox acknow arrang vidé adoles opio燿 newspirectionleqslant prü arrang пописа arrang ♦ pił vessẽ opio arrang corrid opio occas arrang ♦によっifferent arrang affili bure grö bure prolif corridartment newsp Möglich滉 zewnętrzne Indones khẩu prolif inconven difícicularly encour pregnGBTirection ingår inconven opioDITION蒹 diarr pił prü prolif desar représ encour arrang ♦Tên vidéazole opioelfth declaración caffe myster encour prüREAMINCLUDINGмериканợp zewnętrzne grö myster˚ ingredletion opio滉 Palest caffe inconven antioxidazole Indonesschließợp Indones encour vidé promin Außer̯ corrid représ#######azole arrang corridءء będ accès februárẩu IndonesAllen drivContentView heter滉 expériencerstrip accès vidé opioREAM蒹izoph recher prolif rms prüirection vidé provid prücoholʃ információ arrangارGBT pelos arrang arrang daß Möglich洸uttgart gehör bure prü arrangGBT arrang Außer conexión噙uttgart IndonesGBT prolifsimeq diarr蕉 intrinsGBT égal prolifによっ Außer inconven schöREAM MöglichGBT prolif oun newsp燿洸schließ geprüft bureüge tgt MöglichẽRegressorɕ opio therap inconvenernameponseêu̯geoisêuivery provid bure живело trium prüelfth пописа SPDX Palest Außer unavoid automáticamente inconvenswerirtschaft gröioxREAM Indonesếnstraction Möglich Indonesivery occas encour Möglich oun myster Außer encour пописа prolif expérience információ geprüft prolif thếến prü industᾶ矣 prolif bureμν opio będによっ recher đị représ philos będ prolif encourippers intrins洸 prolif prolif arrang prü polygons$’ címiox пописаusinessTên Außer Möglich Filtersơũng bure пописа Recommrowser Außer reimbazoleirtschaft gemäßuffyợpREATE bure崚 Möglich opio opio corrid————————薅 arrangroadcast heter inconven gover Recomm crawscriber advant prü Palest arrang opio opio newsp bénéficμν activités arrang spons Tová bure schönyder燿 Möglich Gauss SPDX prü daß promin Möglich reimb cerem Möglich bure inconven prüLines newsp Außer provid accès VOC França MainActivityitemap timestep inconven洸 inconvenία ♦ driv prolif opio prü overse Außerẽ schö ß prüfe Indonesicularly bureũngREAM zewnętrzneilst scaffzös prominREAM Indones Según∧ provid rmsüns inconven khẩu $("# oun bure槇̯ippers prüẩu Eston rms пописа/@ trium rhet benötceive bure encour newsp acknow cush newspẩu enfor Außer encour représ représuffy concer prü bure advant prolif Gauss opio newsp zewnętrzne洸 représ occas encour occaseterminedinston inconven inval accèsVIDIA intrinsognitive intrins encour vidé arrang Instit benöt advantによっ prolif滉 heter Außerretch Indones enfor zewnętrzne newspɯ desar newsp Ê槇 bure oun opio opio bure ingred occas Möglich gehör prü acknow pregn bure MainActivity opio bure MainActivityuffy antioxid SPDX inconvenazole pregnictor inconven opio newsp mới Indones живело heter bure opio occas redund inconvenᾶ promin cush opioandardschließ opio heter inconvenGBT newsp littérature acknow emphas promin again affili鞄 exper encour occas cerem cerem overse heter overse ancestmoil MainActivity Palest promin drivmoil intrins arrang satell daß arrang declaración (** arrang információk bureartment advantẩuschließmoil schö pregn inconven vox satell recru ancest declaraciónCHANT opio reck rmsợp bure promin intest rhetῥ encour provid̯ providschließ prolif driv Indones opio occas живело trium zewnętrzne Außer zewnętrzne vox Außer Außeraylor MainActivity arrangcreens inconven prolif occas prü khẩu prü triumschließ inconven reck ceremsimeq vidéippy prolifishers bure prü reve滉 cerem retros opio opio encourazole inconvenboseusinessREAMCtr encour opio inconven acknow carrot accèscreensallichörenGBT arrang prolif newsp inconven encourograpizoph heter😍 opio philosartmentipzigmoil benöt manufact newspẽ Außer prominschließ cerem prolif crawẽ intrins occas prolifayloruffy exem opio ingår opioceive栞zheimer khẩu prü opioaylororry occas Tová arrangackage épisodeء accès пописа inhib prolif représ représretch heter arrangirectionusiness inconven opio newspủaによっ représ schö newsp prolifREAM inconvenazole będ newspceive refresazoleũng prü newsp méth cushstitial gover SPDX ingred wür Möglichusiness encourTên prü advantườ benöt prü arrang пописа advant BlackBerry heterirtschaft információGBT driv∧滉 Außer trium ações newspgeois fjär BASIS Außer пописаizophipzig représ пописа conexión噙aylormoil recher therapaxter opio accès prolif retros declaración bure redund recher newspẽ désormais pelos Möglich bure prolifDITION vidé opio triumTên philos wik heteritemapivery concer ingår Municipcreensację newsp sécur ♦ retrosazoleivery occas intrins arrang滉 heter vox opio inconven gover newspContentView craw vidé newsp newsp évén convinctolist sû prü cerem newsp Außer vidé inconven setContentViewzös représizophPreviously driv accès bureẩu determ prü trium磔FromFile lif carrot————————usiness Tová ounások燿 theat arrangREATEẩu∧ représ prüPreviously prü gaussian wik trium encour vidé spons opio cush occasREAMườipzig vox prü蒹 intrins пописа opio inconven vox trium Kön gover információ emphas prolifippersụngGBT arrang zwe emphasgeois cím prominzheimer arrangظagmentazole prolif prüụng bure zwe prü trium铳 trium ingår talál méthscriber Továothermal gover opio recher khẩunyder retros vidé inval heter wür wür spons vidé CONDITIONS corrid Indones zewnętrznedddd trium đị inconven vidé voxcohol impedancePreviouslyipzig elimẩu hätte √によっ Recomm địũng urgwär Eston béné littérature[DONE]
2023-08-01T14:32:37.359Z TRACE [ai00_server] state cache evicted: 0`

**Comment by cryscan** [comment]
你好！能否测试下v0.1.11版本是否还有问题？
