### ISSUE TITLE
如何调用api

### ISSUE THREAD

**Issue by 050603** [cgisky1980/ai00_rwkv_server#20]
能否详细在说明文档中简单列举一下输入输出格式或者头部信息。因为和openaiapi相比，感觉差异还是比较大的。谢谢

**Comment by cgisky1980** [comment]
可以在webui  F12  看一下发送的包   基本兼容openaiAPI

**Comment by cgisky1980** [comment]
也欢迎pr

**Comment by BlinkDL** [comment]
@050603 可以写出你现在的prompt，大家看看，RWKV适合的prompt写法和gpt不同
