### ISSUE TITLE
使用量化好的模型

### ISSUE THREAD

**Issue by Pevernow** [cgisky1980/ai00_rwkv_server#29]
缓存量化结果，使用量化好的模型而不是每次加载都花时间量化，感觉会更好。

**Comment by cgisky1980** [comment]
以后会考虑，这样做可以减少模型体积，但是考虑到计划中lora 动态加载的问题，还是等int4量化和lora加载做完后再考虑一下怎么做比较合适

**Comment by cryscan** [comment]
Done.
