### ISSUE TITLE
运行./ai00_server提示Error: failed to request adaptor

### ISSUE THREAD

**Issue by harold-yh** [cgisky1980/ai00_rwkv_server#3]
运行./ai00_server提示Error: failed to request adaptor
二进制版本：
ai00_server-v0.1.2-x86_64-unknown-linux-gnu.zip
系统版本
Ubuntu 22.04.2 LTS
内核版本：
Linux server 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cgisky1980** [comment]
检查下显卡驱动 VULKAN 是否支持

**Comment by harold-yh** [comment]
> VULKAN

显卡是RTX3090 24G

**Comment by cryscan** [comment]
看看运行`vulkaninfo`的输出？

**Comment by NWater23** [comment]
https://wiki.archlinux.org/title/Vulkan
