### ISSUE TITLE
The generated text starts to be gibberish after around 1000 tokens

### ISSUE THREAD

**Issue by cahya-wirawan** [cgisky1980/ai00_rwkv_server#34]
Hi,

I fine-tuned 1.5B and 7B world model with indonesian dataset. Then I used it with this repo. It generated text is very good, but after around 1000 tokens it starts to concat the words without the spaces and then generate gibberish text. 

I don't have this problem if I use the cryscan repo directly (using the chat.rs and gen.rs script). Both scripts generate nice texts even after 10K tokens. I tested my model also with Blinkd's script https://github.com/BlinkDL/ChatRWKV/blob/main/API_DEMO_WORLD.py and it generates also very good text even after 10K tokens. So, I am wondering what could be the difference between this repo and cryscan repo since this repos based on cryscan repo. 

Could it be an overflow issue after 1000 tokens?

Thanks.

**Comment by cgisky1980** [comment]
There is no difference in the inference section, but the sampler is implemented in AI00. 
The sampler for AI00 is currently slightly simpler, and optimizing the sampler will be the next step.

**Comment by cryscan** [comment]
May you try lower the frequency and presense penalties?

**Comment by cahya-wirawan** [comment]
> May you try lower the frequency and presense penalties?

Do you mean because the white space get high penalties because there too many of them so it is ignored and therefore few words get concatenated? This could be good idea to test. I will try it later at home. Thanks

**Comment by cahya-wirawan** [comment]
Reducing the frequency penalty improves the result, but I have to choose it carefully because if it is too low then I will see many Repetition, if it is too high , I will see the issue where several words concatened or gibberish. 
The change was from
presence penalty=0.5, frequency penalty=0.5
To 
presence penalty=0.7, frequency penalty=0.2

As I mentioned at the beginning that I don’t have this problem using Blinkdl script even using the same presence and frequency penalty of 0.5.

What I see as the different between the implementation in this repo and blink repo is that blink repo uses also alpha decay to reduce the penalties gradually.

**Comment by cahya-wirawan** [comment]
I think this alpha decay quite important otherwise after generating few tausend of tokens, there would be many tokens which have high penalty and will not be taken in to account anymore for text generation. This will give poor text generation result. In my case, the poor result came early just after tausend tokens, so I have to reduce the frequency penalty, but it will just postpone the poor result later.

**Comment by cgisky1980** [comment]
@cahya-wirawan Thx, this will be very helpful

**Comment by cahya-wirawan** [comment]
I wish I had experience with Rust, otherwise I could send a PR to add alpha decay :-)
