### ISSUE TITLE
加快超长文本的state生成？

### ISSUE THREAD

**Issue by Pevernow** [cgisky1980/ai00_rwkv_server#42]
在部分微调中，有效上下文长度已经超过65k甚至到128k。
对于超长上下文的state生成，花费了很久的时间。
而真正生成输出所耗时间极短。
能否加快超长文本的state生成？

**Comment by cryscan** [comment]
天下没有免费的午餐。

**Comment by Pevernow** [comment]
@cryscan 但我发现存在一个很奇怪的问题，似乎和rwkv算法显存效率低下有关。
已知v100半精度算力是3060的五倍。同样采用最新的torch cuda cudnn。
生成10k文本state，v100用时大约3-4秒，3060理论上应该15-20秒完成推理。
但实际情况是，3060花了整整2-3分钟才完成推理。
其中没有爆显存。
3060采用int8量化，照理来讲比fp16还要更快才对。

**Comment by Pevernow** [comment]
数据来自
![image](https://github.com/cgisky1980/ai00_rwkv_server/assets/29888010/a95001e5-fe87-4071-8ab8-93fd3e8d882c)
