### ISSUE TITLE
是否存在基于CUDA的RWKV服务端？

### ISSUE THREAD

**Issue by Pevernow** [cgisky1980/ai00_rwkv_server#43]
由于我使用一些专业卡(A100,V100,P100,T4)，并不支持vulkan。难以使用本项目，是否有支持CUDA的RWKV服务器实现，或者本项目有计划支持？

**Comment by cgisky1980** [comment]
建议用runner   
本项目主要目标是 个人PC、消费级显卡上跑 RWKV。

**Comment by tastypear** [comment]
@Pevernow T4是可以使用vulkan的，例如colab，需要先 `!apt install libnvidia-gl-535`
