### ISSUE TITLE
convert_file() got multiple values for argument 'rename'

### ISSUE THREAD

**Issue by nopepper** [cgisky1980/ai00_rwkv_server#54]
There's currently an issue in line 62 of the conversion script, as noted here:
https://github.com/cgisky1980/ai00_rwkv_server/commit/4eaaa3ce4c892610f54fb6aabff3927bf5e59b05#commitcomment-133923059

The error message is `TypeError: convert_file() got multiple values for argument 'rename'`. This happens because both `["lora_A"]` and `{time_faaa: ...}` are passed as the `reponse` argument, once as a positional argument, once as a keyword arg.

**Comment by cryscan** [comment]
Thanks. Should be resolved now.
